NREL/wex

- src/dview/dvtimeseriesdataset.cpp
- src/lkscript.cpp
- src/plot/plcontourplot.cpp
- src/plot/plplot.cpp
These changes suppress -Wreorder warnings from g++.
> Reorder class member initialisations so that they are appear in declaration order

- src/dview/dvfilereader.cpp
- src/registration.cpp
In one case, it's easy to check the return value of fgets(). In the other, we use the proper C++ standard library to avoid the less safe C library functions.
> Re-work use of 'fgets' to eliminate g++ unchecked return value warnings

- src/codeedit.cpp
I have replaced the char * string constants with std::strings.
> Fix ISO C++ forbids converting a string constant to 'char *' warnings.

- src/diurnal.cpp
- src/lkscript.cpp
- src/metro.cpp
- src/plot/plaxis.cpp
In most cases, these were fixed by removing unnecessary casts. The natural type of wxWidget's size() and other methods is size_t, which is unsigned. So in most cases, casts to int were causing the warnings unnecessarily. In one case, I used static_cast<>.
> Fix many signed and unsigned integer comparison warnings from g++

- src/jsonreader.cpp
- src/jsonval.cpp
- src/jsonwriter.cpp
- src/pdf/pdfdc.cpp
Using these wxWidgets macros to prevent these static variables being defined unless using wxWidgets
logging and/or debugging. Without this, the wx logging and debugging macros expand to nothing and so the variables produce unused variable warnings.
> Guard static variable declarations with wxUSE_LOG_TRACE and wxDEBUG_LEVEL

- .travis.yml
This is a working .travis.yml file that can be used with Travis CI for continuous integration builds and testing. At the moment, warnings are not picked up, but could be if -Werror is included in CXXFLAGS.
> Add a .travis.yml file for continuous integration via Travis CI.

- src/plot/plcontourplot.cpp
`libqhull` is a C library being called from the C++ source base. It's a nightmare fixing all of the use of string literals throughout the library, so the easiest thing to do is use a `const_cast` on entry to the library. I think that is a reasonable approach.
> Fix warning about loss of constness.

- build_linux/Makefile
I am not completely sure why others can build on Linux without this patch. Without it, `ltlcdfil.o` isn't built which means `FT_Library_SetLcdFilter` isn't defined. Anyway, this seems to fix a lot of issues for me!
> Makefile (OBJECTS): Add ftlcdfil.o.

- src/dview/dvfilereader.cpp
Fixes #41 .You can test the behavior on the attached file.  I've simple removed data for each of the columns in the first or second row.  It will go through all columns and alert the user if data is missing in that column.  If all columns are missing data, this could be burdensome, but might be good to alert user.  Alternate could be to implement more complex dialog with a "Yes to all" or something.
[MissingDataExample.zip](https://github.com/NREL/wex/files/1518908/MissingDataExample.zip)
https://www.pivotaltracker.com/story/show/153268630
> Handle missing data by replacing with 0 and warning user

- src/pdf/pdffontparsertruetype.cpp
This is not needed -- it's an unused static variable. This change has already been accepted upstream: utelle/wxpdfdoc@8991cecb7671f481b261c9f685ec729b8f071e31
> * src/pdf/pdffontparsertruetype.cpp (tableNamesDefault): Remove.

- build_linux/Makefile
Disabling these warnings (unused variables and functions) for a very small subset of the source files is safe enough as there is no risk of missing serious problems.
> Set EXTRA_WARN_FLAGS for a number of 3rd party source files that produce undesirable warnings

- include/wex/dview/dvpncdfctrl.h
- include/wex/dview/dvstatisticstablectrl.h
- include/wex/lkscript.h
- include/wex/pdf/pdfcffdecoder.h
- include/wex/pdf/pdffontsubsetcff.h
- include/wex/pdf/pdfpattern.h
- include/wex/pdf/pdfshape.h
- include/wex/pdf/pdfxml.h
- include/wex/radiochoice.h
- include/wex/uiform.h
- src/pdf/pdfcffdecoder.cpp
- src/pdf/pdfencrypt.cpp
- src/pdf/pdffontsubsetcff.cpp
This gets rid of almost all of the remaining warnings in WEX.
> Fix an assortment of remaining warnings.

- src/dview/dvtimeseriesctrl.cpp
Fix issue #65 - Default to unstacked chart for all timeseries
> Fix #65 - Default to unstacked chart

- src/ole/excelauto.cpp
Import empty Excel cells as an empty string rather than a 0
> xl_get function: blank entry instead of 0 for empty cells

- src/dview/dvfilereader.cpp
TMY2/TMY3/EPW files have the dew point mislabeled as wetbulb temperature ("Wet Temp"). These files don't have wetbulb temperatures defined at all.
References:
- EPW: https://bigladdersoftware.com/epx/docs/8-9/auxiliary-programs/energyplus-weather-file-epw-data-dictionary.html#field-dew-point-temperature
- TMY3: http://www.nrel.gov/docs/fy08osti/43156.pdf
- TMY2: https://rredc.nrel.gov/solar/pubs/tmy2/tab3-2.html
cc @jmaguire1
> Fix mislabeling of dew point

- src/plot/qhull/rboxlib.c
This patch makes the source buffer (`seedbuf`) one character shorter than the destination buffer (`command`) so that G++ does not warn about cases where there may be insufficient space for the null terminator in the destination string.
> Silence G++ warning about strncat

- src/codeedit.cpp
This patch removes a call to a deprecated wxWidgets method, `wxCodeEditControl::SetStyleBits`.  According to my reading of the wxWidgets and Scintilla manuals, we can just do away with this without any other changes.
G++ `-Wall` warns around deprecated functions and so this was warning.
> Remove deprecated wxWidgets method wxCodeEditControl::SetStyleBits

- src/pdf/pdfcjkfontdata.inc
This has been fixed in the upstream wxpdfdoc sources as well. See https://github.com/utelle/wxpdfdoc/issues/69
> Silence g++ warnings in wxpdfdoc about unused variables for some CJK fonts

- src/clipper/clipper.cpp
This patch adds initialisation for simple types in `struct TEdge` and then explicitly initialises each `TEdge` when creating the edge array. This allows the `memset` call in `InitEdge()` to be removed, eliminating this G++ warning:
```
/home/bje/source/wex/src/clipper/clipper.cpp:643:40: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct ClipperLib::TEdge’; use assignment or value-initialization instead [-Wclass-memaccess]
```
> Eliminate G++ class-memaccess warning in clipper.cpp

- .travis.yml
Set `CFLAGS` and `CXXFLAGS` to `-Werror` so that these are included in the CMake compiler flags when building through Travis CI.
It is best to not impose `-Werror` on users trying to build this library for themselves as local issues could produce spurious warnings that will cause the build to fail -- and users to complain.
> Set CFLAGS and CXXFLAGS to -Werror for Travis CI

- CMakeLists.txt
CMake option names should be prepended to avoid potential name collisions when SAM source code is included in other projects.
> rename skip_tools to SAM_SKIP_TOOLS

- src/codeedit.cpp
- src/plot/ploutdev.cpp
Re enable FREETYPE_TEXT to remove blurry graphs on MacOS - closes SAM #462
> MacOS test to address SAM issue 462

- .github/workflows/ci.yml
- tools/CMakeLists.txt
Follow up on https://github.com/NREL/SolTrace/pull/33
Any idea on how to run the tests? Thanks
> Add Continuous Integration for Linux with GitHub Actions

- .github/workflows/ci.yml
- include/wex/dview/dvselectionlist.h
- src/dview/dvselectionlist.cpp
Defaults and UI for new hybrid configurations for Single Owner and Host Developer financial models:
PVWatts Wind Battery Hybrid
PVWatts Wind FuelCell Battery Hybrid
Photovoltaic Wind Battery Hybrid
Generic PVWatts Wind FuelCell Battery Hybrid
Goes with:
* https://github.com/NREL/SAM/pull/1448
* https://github.com/NREL/ssc/pull/1051
> New Hybrid Configurations

- src/plot/plaxis.cpp
Please test with lifetime, single year, hourly and sub-hourly files.
Please test for Feb 29 in out years as described in https://github.com/NREL/SAM/issues/289
Please test transitions between years (Dec to Jan) at various zoom levels.
Test file - detailed PV residential here 
[SAM_289.zip](https://github.com/user-attachments/files/17646381/SAM_289.zip)
> Address SAM issue 289 - ignore leap years in timeseries axis

- include/wex/plot/plcolourmap.h
- src/plot/plcolourmap.cpp
- src/plot/plcontourplot.cpp
-Rather than drawing nonfinite results as the minimum color in contour plots, draw them as light grey
-Start from the minimum value for contour layer plotting rather than min value + 1; previously, contour made min color the background then counted from the next layer
-Light grey preset is now background color before any layers are drawn
-Useful in parametrics with Nan or inf values in outputs, such as payback period or internal rate of return
> Change mask color for nan/inf values to light grey for contour plots

- src/dview/dvdmapctrl.cpp
Refers to  per https://github.com/NREL/SAM/issues/1616
To test use weather files and project files here 
[SAM_1616.zip](https://github.com/user-attachments/files/19602029/SAM_1616.zip)
Test in 2024.12.12 release and check "Heat map" for sub hourly simulations, e.g. 5min weather file
Build with SAM_1616 branch of wex and develop branches of other repos and expect to see
> Fix wxDVDMapPlot dithering issue for sub-hourly timesteps
